### ISSUE TITLE
Video Player

### ISSUE THREAD

**Issue by Femlives** [Femlives/femlives#30]
We need to prototype the video player. Let's
- build a video player component that accepts a srcUrl prop
- set up a page with
   - video player
   - input form where we can set the srcUrl

So the user story would be:
Simon is prototyping the video database and needs a way to see whether or not the uploaded video is working. He visits the route `femlives/video-prototype` and copy/pastes the url of the uploaded test-video in the input form and presses submit. The video player loads the video and Simon can press play to start the video.

**Comment by daryafurman** [comment]
Closes #35

**Comment by daryafurman** [comment]
#34

**Comment by daryafurman** [comment]
Closes #34
